# Generated by Django 3.2.11 on 2022-01-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_banned',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
